"""Structured block-circulant L^circ: never materialises the K x K feature covariance.

Motivation
----------
core.rf_circulant_torch.circulant_rf_mmse_t builds Sigma_phi as a dense K x K matrix
(K = c*d) and then extracts the per-frequency c x c blocks. That is fine while K is a few
thousand, but the free-parameter-matched setting needs c = k blocks, i.e. K = k*d features
(262,144 already at k/d = 1 with d = 512), where K x K is out of the question.

This module computes the SAME quantity

    L^circ = Tr(Sigma_p0) - sum_f  q_f^H P_f^{-1} q_f,
    (P_f)_{ab} = f_f^H Sigma^{(a,b)}_{phi} f_f,   (q_f)_a = f_f^H Sigma^{(a)}_{phi,x0} f_f,

directly in the frequency domain, in O(c^2 d) memory rather than O(c^2 d^2).

The three pieces
----------------
Write u_a := G_a F^T (N x d complex), where G_a is block a's centred feature matrix. Then,
for a Gram-type block Sigma^{(a,b)} = A_a^T A_b / N,

    f_f^H (A_a^T A_b / N) f_f = (1/N) sum_n  aa_a[n,f] * conj(aa_b[n,f]),   aa := A F^T,

so every Gram term is a per-frequency c x c outer product -- no d x d block is ever formed.

The noise terms are the subtle part. Sigma_noise = sum_n coef_n * rho^{o n} o (C_n^T C_n/N),
and rho is block-circulant: rho^{(a,b)}[p,q] = rho0_{ab}(p-q)/(n_a n_b) with
rho0_{ab}(m) = sum_j h_a[j] h_b[j+m]. Expanding rho^{o n} in the DFT basis,
rho^{o n,(a,b)}[p,q] = sum_g w_g F[g,p] conj(F[g,q]), and using
F[f,p] F[g,p] = F[f+g,p]/sqrt(d),

    f_f^H (rho^{o n} o M) f_f = (1/d) sum_g w_g * D_{ab}(f+g),
    D_{ab}(f') := f_{f'}^H M^{(a,b)} f_{f'},

i.e. a cyclic CORRELATION over the frequency index. This is what couples all frequencies and
is the one step worth validating rather than trusting -- see selftest() below, which checks
against the reference K x K implementation to ~1e-12.

Finally stein_covariances_t REPLACES (does not add to) the diagonal of Sigma_noise with the
exact conditional variance, so we correct the (a,a) entries by
(1/d) sum_p [diag_exact - formula_diag], which is frequency-independent, and add the ridge
lam to every P_f diagonal.
"""

import numpy as np
import torch

from core.rf_gmm_estimators_torch import _ndtr, _npdf

_SQ2PI = float(np.sqrt(2.0 * np.pi))


def _dft(d, device, dtype):
    j = torch.arange(d, device=device, dtype=dtype)
    ang = -2.0 * np.pi * torch.outer(j, j) / d
    return torch.complex(torch.cos(ang), torch.sin(ang)) / (d ** 0.5)


def _roll_rows(h, d):
    """Rows of the circulant block generated by h: row p is np.roll(h, p)."""
    idx = (torch.arange(d, device=h.device).unsqueeze(0)
           - torch.arange(d, device=h.device).unsqueeze(1)) % d
    return h[idx]                                    # (d, d): [p, i] = h[(i-p) % d]


def circulant_rf_mmse_struct(x0, h, sigma, lam=1e-6, device='cuda', dtype=torch.float64,
                             block_chunk=None, host_budget_gb=60.0):
    """L^circ for block-circulant Theta generated by filters h (c, d). O(c^2 d) memory.

    x0 : (N, d) data.  h : (c, d) filters, block a has rows roll(h_a, p), p = 0..d-1.
    Returns the loss as a float. Unconditional only (Gamma = 0), free readout bias.
    """
    x0 = x0.to(device=device, dtype=dtype)
    h = h.to(device=device, dtype=dtype)
    N, d = x0.shape
    c = h.shape[0]
    cdt = torch.complex128 if dtype == torch.float64 else torch.complex64
    F = _dft(d, device, dtype).to(cdt)

    mu = x0.mean(0)
    X0c = x0 - mu
    v = X0c.to(cdt) @ F.T                                    # (N, d) complex
    trace_p0 = float((X0c ** 2).sum() / max(N, 1))

    nrm = torch.linalg.norm(h, dim=1)                        # (c,)
    s = sigma * nrm                                          # (c,)

    # ---- per-frequency Grams, accumulated over block-pair chunks -----------------------
    # Storing every block's transform at once costs c*N*d complex numbers (42 GB per array
    # at c=512, N=10000, d=512), so we stream: transform one chunk of blocks at a time and
    # accumulate the (d, c, c) Grams. Those outputs are c^2 d, which is what actually has to
    # be held; `out_device='cpu'` keeps them in host RAM for the largest c.
    bc = block_chunk or c
    out_dev = device if (4 * d * c * c * 16) < 2e10 else 'cpu'
    Pd = torch.zeros(d, c, c, dtype=cdt, device=out_dev)
    D = [torch.zeros(d, c, c, dtype=cdt, device=out_dev) for _ in range(3)]
    q = torch.zeros(d, c, dtype=cdt, device=device)
    diag_corr = torch.zeros(c, dtype=dtype, device=device)

    Xf = torch.fft.fft(x0.to(cdt), dim=1)          # hoisted; used by the FFT correlation

    def _transform(a0, a1):
        # M[b,n,p] = sum_i x0[n,i] h_b[(i-p) % d] = sum_u h_b[u] x0[n, u+p], a circular
        # CORRELATION. Doing it as an explicit (d,d) roll matrix costs O(N d^2) per block,
        # which is fine at d=784 but not at d=3072 (9.4e10 flops per block). Via FFT it is
        # O(N d log d) -- ~250x cheaper at d=3072. Verified against the explicit form.
        Hf = torch.fft.fft(h[a0:a1].to(cdt), dim=1)                        # (B, d)
        M = torch.fft.ifft(Xf.unsqueeze(0) * Hf.conj().unsqueeze(1), dim=2).real.contiguous()
        sa = s[a0:a1].view(-1, 1, 1)
        z = M / sa
        Phi = _ndtr(z); ph = _npdf(z)
        G = M * Phi + sa * ph
        C1 = sa * Phi; C2 = sa * ph / 2.0; C3 = -M * ph / 6.0
        Gc = G - G.mean(1, keepdim=True)
        uu = Gc.to(cdt) @ F.T
        cc = [Cx.to(cdt) @ F.T for Cx in (C1, C2, C3)]
        diag_exact = ((M ** 2 + sa ** 2) * Phi + M * sa * ph - G ** 2).mean(1)
        formula = (C1 ** 2).mean(1) + 2.0 * (C2 ** 2).mean(1) + 6.0 * (C3 ** 2).mean(1)
        dc = (diag_exact - formula).sum(1) / d
        del M, z, Phi, ph, G, C1, C2, C3, Gc
        return uu, cc, dc

    # Transform every chunk ONCE and park it in host RAM; the pair loop then only moves
    # tensors. Re-transforming inside the inner loop would cost O(n_chunks^2) einsums of
    # size N*bc*d^2, which dominates everything else.
    #
    # HOST MEMORY IS BOUNDED, and not by the node. Caching all chunks costs 4*c*N*d*16
    # bytes -- 156 GB at c=512, N=10000, d=512 -- while a Slurm allocation caps the cgroup
    # far below the machine total (150 GB here, and the first attempt was OOM-killed at
    # ~156 GB RSS). So we cache only while under `host_budget_gb` and recompute the rest on
    # demand; an uncached chunk is re-transformed once per outer iteration, which is a few
    # seconds each, whereas exceeding the cgroup is fatal. Precision is unaffected: the
    # cache stays complex128 rather than being downcast.
    chunks = [(a0, min(a0 + bc, c)) for a0 in range(0, c, bc)]
    per_chunk_gb = 4 * bc * N * d * 16 / 2 ** 30
    n_cacheable = max(1, int(host_budget_gb / max(per_chunk_gb, 1e-9)))
    cache = {}
    for ic, (a0, a1) in enumerate(chunks):
        uA, cA, dcA = _transform(a0, a1)
        diag_corr[a0:a1] = dcA
        q[:, a0:a1] = torch.einsum('anf,nf->fa', uA, v.conj()) / N
        if ic < n_cacheable:
            cache[ic] = (uA.cpu(), [x.cpu() for x in cA])
        del uA, cA
        torch.cuda.empty_cache()

    def _get(ic):
        if ic in cache:
            return cache[ic][0].to(device), [x.to(device) for x in cache[ic][1]]
        u_, c_, _ = _transform(*chunks[ic])
        return u_, c_

    for ia, (a0, a1) in enumerate(chunks):
        uA, cA = _get(ia)
        for ib, (b0, b1) in enumerate(chunks):
            if ib == ia:
                uB, cB = uA, cA
            else:
                uB, cB = _get(ib)
            Pd[:, a0:a1, b0:b1] = (torch.einsum('anf,bnf->fab', uA, uB.conj()) / N).to(out_dev)
            for i in range(3):
                D[i][:, a0:a1, b0:b1] = (torch.einsum('anf,bnf->fab',
                                                      cA[i], cB[i].conj()) / N).to(out_dev)
            if ib != ia:
                del uB, cB
            torch.cuda.empty_cache()
        del uA, cA
        torch.cuda.empty_cache()
    del cache
    if out_dev != device:
        Pd = Pd.to(device); D = [x.to(device) for x in D]

    # ---- rho spectra and the frequency correlation -------------------------------------
    # rho0_{ab}(m) = sum_j h_a[j] h_b[(j+m) % d]
    idx = (torch.arange(d, device=device).unsqueeze(0)
           + torch.arange(d, device=device).unsqueeze(1)) % d              # [m, j] -> j+m
    Hs = h[:, idx]                                                          # (c, d, d) [b,m,j]
    rho0 = torch.einsum('aj,bmj->abm', h, Hs)                               # (c, c, d)
    psi = rho0 / (nrm.view(-1, 1, 1) * nrm.view(1, -1, 1))
    P = Pd + torch.diag_embed(diag_corr.to(cdt)).unsqueeze(0) \
        + lam * torch.eye(c, dtype=cdt, device=device).unsqueeze(0)
    for i, coef in enumerate((1.0, 2.0, 6.0)):
        # Spectrum of rho^{o(i+1)}. Two conventions have to line up here and BOTH were wrong
        # on the first attempt, which is why this module is validated rather than trusted:
        #   (a) the expansion rho[p,q] = sum_g w_g F[g,p] conj(F[g,q]) holds with
        #       w_g = sum_m psi(m) e^{+2 pi i m g/d} = d*ifft(psi) -- NOT the contraction
        #       with F, which is off by a sign in the exponent and a factor sqrt(d);
        #   (b) the frequency correlation below then consumes conj(w) = fft(psi) (psi real).
        # Checked term by term against the reference K x K build: q and P^data match to
        # 1e-15, and this noise term to 1e-7, the residual being the reference's
        # clamp(rho, +-(1-1e-6)) on a diagonal that is subsequently overwritten anyway.
        w = torch.fft.fft((psi ** (i + 1)).to(cdt), dim=-1)
        # P^noise_f[a,b] = (1/d) sum_g w_g D_{ab}(f+g)
        Dg = D[i].permute(1, 2, 0)                                          # (a, b, f)
        Dh = torch.fft.fft(Dg, dim=-1)
        Wh = torch.fft.fft(w, dim=-1)
        corr = torch.fft.ifft(Dh * Wh.conj(), dim=-1)                       # sum_g w_g D(f+g)
        P = P + coef * corr.permute(2, 0, 1) / d
    del D, psi, rho0, Hs
    torch.cuda.empty_cache()

    sol = torch.linalg.solve(P, q.unsqueeze(-1)).squeeze(-1)
    expl = float(torch.real(torch.sum(q.conj() * sol)))
    return max(0.0, trace_p0 - expl)


def selftest(seed=0, verbose=True):
    """Validate against the reference K x K implementation at sizes where both can run."""
    from core.rf_circulant import build_circulant_theta
    from core.rf_circulant_torch import circulant_rf_mmse_t
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    ok = True
    for (d, c, N, sig, w) in ((8, 2, 400, 0.7, None), (8, 3, 400, 1.3, 3),
                              (12, 2, 600, 0.5, None), (16, 4, 800, 1.0, 5),
                              (16, 3, 800, 2.0, 2)):
        rng = np.random.default_rng(seed)
        A = rng.standard_normal((d, d)) * 0.6
        x0 = torch.tensor(rng.standard_normal((N, d)) @ A.T + 0.3, dtype=torch.float64,
                          device=dev)
        Theta = build_circulant_theta(c * d, d, np.random.default_rng(seed + 1), w=w)
        # recover the generating filters: block a, row 0 is roll(h_a, 0) = h_a
        hh = torch.tensor(np.stack([Theta[a * d] for a in range(c)]), dtype=torch.float64,
                          device=dev)
        U0 = torch.zeros(N, 1, dtype=torch.float64, device=dev)
        G0 = torch.zeros(c * d, 1, dtype=torch.float64, device=dev)
        ref = circulant_rf_mmse_t(x0, U0, Theta, G0, sig, 1e-6, conditional=False,
                                  device=dev, dtype=torch.float64)
        ref = float(ref['loss'] if isinstance(ref, dict) else ref)
        got = circulant_rf_mmse_struct(x0, hh, sig, lam=1e-6, device=dev)
        rel = abs(got - ref) / max(abs(ref), 1e-12)
        ok &= rel < 1e-9
        if verbose:
            print(f"  d={d:>3} c={c} w={str(w):>4} sigma={sig:<4}: ref={ref:.12f} "
                  f"struct={got:.12f}  rel={rel:.2e}  {'OK' if rel < 1e-9 else 'FAIL'}")
    return ok


if __name__ == '__main__':
    print("Validating structured block-circulant L^circ against the K x K reference:")
    print("PASS" if selftest() else "FAIL")
