"""Structured block-circulant L^circ: never materialises the K x K feature covariance.

Motivation
----------
core.rf_circulant_torch.circulant_rf_mmse_t builds Sigma_phi as a dense K x K matrix
(K = c*d) and then extracts the per-frequency c x c blocks. That is fine while K is a few
thousand, but the free-parameter-matched setting needs c = k blocks, i.e. K = k*d features
(262,144 already at k/d = 1 with d = 512), where K x K is out of the question.

This module computes the SAME quantity

    L^circ = Tr(Sigma_p0) - sum_f  q_f^H P_f^{-1} q_f,
    (P_f)_{ab} = f_f^H Sigma^{(a,b)}_{phi} f_f,   (q_f)_a = f_f^H Sigma^{(a)}_{phi,x0} f_f,

directly in the frequency domain, in O(c^2 d) memory rather than O(c^2 d^2).

The three pieces
----------------
Write u_a := G_a F^T (N x d complex), where G_a is block a's centred feature matrix. Then,
for a Gram-type block Sigma^{(a,b)} = A_a^T A_b / N,

    f_f^H (A_a^T A_b / N) f_f = (1/N) sum_n  aa_a[n,f] * conj(aa_b[n,f]),   aa := A F^T,

so every Gram term is a per-frequency c x c outer product -- no d x d block is ever formed.

The noise terms are the subtle part. Sigma_noise = sum_n coef_n * rho^{o n} o (C_n^T C_n/N),
and rho is block-circulant: rho^{(a,b)}[p,q] = rho0_{ab}(p-q)/(n_a n_b) with
rho0_{ab}(m) = sum_j h_a[j] h_b[j+m]. Expanding rho^{o n} in the DFT basis,
rho^{o n,(a,b)}[p,q] = sum_g w_g F[g,p] conj(F[g,q]), and using
F[f,p] F[g,p] = F[f+g,p]/sqrt(d),

    f_f^H (rho^{o n} o M) f_f = (1/d) sum_g w_g * D_{ab}(f+g),
    D_{ab}(f') := f_{f'}^H M^{(a,b)} f_{f'},

i.e. a cyclic CORRELATION over the frequency index. This is what couples all frequencies and
is the one step worth validating rather than trusting -- see selftest() below, which checks
against the reference K x K implementation to ~1e-12.

Finally stein_covariances_t REPLACES (does not add to) the diagonal of Sigma_noise with the
exact conditional variance, so we correct the (a,a) entries by
(1/d) sum_p [diag_exact - formula_diag], which is frequency-independent, and add the ridge
lam to every P_f diagonal.
"""

import numpy as np
import torch

from core.rf_gmm_estimators_torch import _ndtr, _npdf

_SQ2PI = float(np.sqrt(2.0 * np.pi))


def _dft(d, device, dtype):
    j = torch.arange(d, device=device, dtype=dtype)
    ang = -2.0 * np.pi * torch.outer(j, j) / d
    return torch.complex(torch.cos(ang), torch.sin(ang)) / (d ** 0.5)


def _roll_rows(h, d):
    """Rows of the circulant block generated by h: row p is np.roll(h, p)."""
    idx = (torch.arange(d, device=h.device).unsqueeze(0)
           - torch.arange(d, device=h.device).unsqueeze(1)) % d
    return h[idx]                                    # (d, d): [p, i] = h[(i-p) % d]


def circulant_rf_mmse_struct(x0, h, sigma, lam=1e-6, device='cuda', dtype=torch.float64,
                             block_chunk=None, host_budget_gb=60.0, sample_chunk=64):
    """L^circ for block-circulant Theta generated by filters h (c, d). O(c^2 d) memory.

    x0 : (N, d) data.  h : (c, d) filters, block a has rows roll(h_a, p), p = 0..d-1.
    Returns the loss as a float. Unconditional only (Gamma = 0), free readout bias.
    """
    x0 = x0.to(device=device, dtype=dtype)
    h = h.to(device=device, dtype=dtype)
    N, d = x0.shape
    c = h.shape[0]
    cdt = torch.complex128 if dtype == torch.float64 else torch.complex64
    F = _dft(d, device, dtype).to(cdt)

    mu = x0.mean(0)
    X0c = x0 - mu
    v = X0c.to(cdt) @ F.T                                    # (N, d) complex
    trace_p0 = float((X0c ** 2).sum() / max(N, 1))

    nrm = torch.linalg.norm(h, dim=1)                        # (c,)
    s = sigma * nrm                                          # (c,)

    # ---- per-frequency Grams, accumulated over block-pair chunks -----------------------
    # Storing every block's transform at once costs c*N*d complex numbers (42 GB per array
    # at c=512, N=10000, d=512), so we stream: transform one chunk of blocks at a time and
    # accumulate the (d, c, c) Grams. Those outputs are c^2 d, which is what actually has to
    # be held; `out_device='cpu'` keeps them in host RAM for the largest c.
    bc = block_chunk or c
    out_dev = device if (4 * d * c * c * 16) < 2e10 else 'cpu'
    Pd = torch.zeros(d, c, c, dtype=cdt, device=out_dev)
    D = [torch.zeros(d, c, c, dtype=cdt, device=out_dev) for _ in range(3)]
    q = torch.zeros(d, c, dtype=cdt, device=device)
    diag_corr = torch.zeros(c, dtype=dtype, device=device)

    Xf = torch.fft.fft(x0.to(cdt), dim=1)          # hoisted; used by the FFT correlation

    def _transform_samples(n0, n1):
        """Transform ALL c blocks for samples [n0,n1). Returns DFT'd features and the
        unnormalised diagonal-correction contribution for this sample batch."""
        Hf = torch.fft.fft(h.to(cdt), dim=1)                                # (c, d)
        M = torch.fft.ifft(Xf[n0:n1].unsqueeze(0) * Hf.conj().unsqueeze(1), dim=2).real
        sa = s.view(-1, 1, 1)
        z = M / sa
        Phi = _ndtr(z); ph = _npdf(z)
        G = M * Phi + sa * ph
        C1 = sa * Phi; C2 = sa * ph / 2.0; C3 = -M * ph / 6.0
        Gc = G - gmean.unsqueeze(1)
        uu = Gc.to(cdt) @ F.T
        cc = [Cx.to(cdt) @ F.T for Cx in (C1, C2, C3)]
        de = ((M ** 2 + sa ** 2) * Phi + M * sa * ph - G ** 2).sum(1)
        fo = (C1 ** 2).sum(1) + 2.0 * (C2 ** 2).sum(1) + 6.0 * (C3 ** 2).sum(1)
        dcs = (de - fo).sum(1) / d
        del M, z, Phi, ph, G, C1, C2, C3, Gc
        return uu, cc, dcs

    # Per-(block, position) feature mean, needed to centre G. This is a (c, d) object, NOT
    # one scalar per block: G is centred over SAMPLES at each position independently.
    gmean = torch.zeros(c, d, dtype=dtype, device=device)
    _nb0 = max(1, min(N, int(sample_chunk)))
    _Hf = torch.fft.fft(h.to(cdt), dim=1)
    for n0 in range(0, N, _nb0):
        n1 = min(n0 + _nb0, N)
        M = torch.fft.ifft(Xf[n0:n1].unsqueeze(0) * _Hf.conj().unsqueeze(1), dim=2).real
        sa = s.view(-1, 1, 1); z = M / sa
        gmean += (M * _ndtr(z) + sa * _npdf(z)).sum(1)
        del M, z
    gmean /= N

    # ---- accumulate by chunking over SAMPLES, not blocks --------------------------------
    # P_f[a,b] = (1/N) sum_n uhat_a[n,f] conj(uhat_b[n,f]) is a SUM OVER SAMPLES, so it can
    # be accumulated a batch of n at a time with all c blocks resident. Chunking over BLOCKS
    # instead (the earlier design) forces every block to be available for the cross terms,
    # so any block that does not fit the host cache is re-transformed once per outer
    # iteration -- 3,776 redundant transforms at c=256, which is what made the raw-pixel run
    # take 10 h instead of the predicted 1.5 h. Chunking over samples transforms each sample
    # EXACTLY ONCE and makes peak memory c*n_b*d, tunable via n_b independently of c
    # (3.0 GB at c=256, d=3072, n_b=64).
    nb = max(1, min(N, int(sample_chunk)))
    for n0 in range(0, N, nb):
        n1 = min(n0 + nb, N)
        uu, cc, dcs = _transform_samples(n0, n1)
        Pd += (torch.einsum('anf,bnf->fab', uu, uu.conj())).to(out_dev)
        for i in range(3):
            D[i] += (torch.einsum('anf,bnf->fab', cc[i], cc[i].conj())).to(out_dev)
        q += torch.einsum('anf,nf->fa', uu, v[n0:n1].conj())
        diag_corr += dcs
        del uu, cc
        torch.cuda.empty_cache()
    Pd /= N; q /= N
    for i in range(3):
        D[i] /= N
    diag_corr /= N

    if out_dev != device:
        Pd = Pd.to(device); D = [x.to(device) for x in D]

    # ---- rho spectra and the frequency correlation -------------------------------------
    # rho0_{ab}(m) = sum_j h_a[j] h_b[(j+m) % d]
    idx = (torch.arange(d, device=device).unsqueeze(0)
           + torch.arange(d, device=device).unsqueeze(1)) % d              # [m, j] -> j+m
    Hs = h[:, idx]                                                          # (c, d, d) [b,m,j]
    rho0 = torch.einsum('aj,bmj->abm', h, Hs)                               # (c, c, d)
    psi = rho0 / (nrm.view(-1, 1, 1) * nrm.view(1, -1, 1))
    P = Pd + torch.diag_embed(diag_corr.to(cdt)).unsqueeze(0) \
        + lam * torch.eye(c, dtype=cdt, device=device).unsqueeze(0)
    for i, coef in enumerate((1.0, 2.0, 6.0)):
        # Spectrum of rho^{o(i+1)}. Two conventions have to line up here and BOTH were wrong
        # on the first attempt, which is why this module is validated rather than trusted:
        #   (a) the expansion rho[p,q] = sum_g w_g F[g,p] conj(F[g,q]) holds with
        #       w_g = sum_m psi(m) e^{+2 pi i m g/d} = d*ifft(psi) -- NOT the contraction
        #       with F, which is off by a sign in the exponent and a factor sqrt(d);
        #   (b) the frequency correlation below then consumes conj(w) = fft(psi) (psi real).
        # Checked term by term against the reference K x K build: q and P^data match to
        # 1e-15, and this noise term to 1e-7, the residual being the reference's
        # clamp(rho, +-(1-1e-6)) on a diagonal that is subsequently overwritten anyway.
        w = torch.fft.fft((psi ** (i + 1)).to(cdt), dim=-1)
        # P^noise_f[a,b] = (1/d) sum_g w_g D_{ab}(f+g)
        Dg = D[i].permute(1, 2, 0)                                          # (a, b, f)
        Dh = torch.fft.fft(Dg, dim=-1)
        Wh = torch.fft.fft(w, dim=-1)
        corr = torch.fft.ifft(Dh * Wh.conj(), dim=-1)                       # sum_g w_g D(f+g)
        P = P + coef * corr.permute(2, 0, 1) / d
    del D, psi, rho0, Hs
    torch.cuda.empty_cache()

    sol = torch.linalg.solve(P, q.unsqueeze(-1)).squeeze(-1)
    expl = float(torch.real(torch.sum(q.conj() * sol)))
    return max(0.0, trace_p0 - expl)


def selftest(seed=0, verbose=True):
    """Validate against the reference K x K implementation at sizes where both can run."""
    from core.rf_circulant import build_circulant_theta
    from core.rf_circulant_torch import circulant_rf_mmse_t
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    ok = True
    for (d, c, N, sig, w) in ((8, 2, 400, 0.7, None), (8, 3, 400, 1.3, 3),
                              (12, 2, 600, 0.5, None), (16, 4, 800, 1.0, 5),
                              (16, 3, 800, 2.0, 2)):
        rng = np.random.default_rng(seed)
        A = rng.standard_normal((d, d)) * 0.6
        x0 = torch.tensor(rng.standard_normal((N, d)) @ A.T + 0.3, dtype=torch.float64,
                          device=dev)
        Theta = build_circulant_theta(c * d, d, np.random.default_rng(seed + 1), w=w)
        # recover the generating filters: block a, row 0 is roll(h_a, 0) = h_a
        hh = torch.tensor(np.stack([Theta[a * d] for a in range(c)]), dtype=torch.float64,
                          device=dev)
        U0 = torch.zeros(N, 1, dtype=torch.float64, device=dev)
        G0 = torch.zeros(c * d, 1, dtype=torch.float64, device=dev)
        ref = circulant_rf_mmse_t(x0, U0, Theta, G0, sig, 1e-6, conditional=False,
                                  device=dev, dtype=torch.float64)
        ref = float(ref['loss'] if isinstance(ref, dict) else ref)
        got = circulant_rf_mmse_struct(x0, hh, sig, lam=1e-6, device=dev)
        rel = abs(got - ref) / max(abs(ref), 1e-12)
        ok &= rel < 1e-9
        if verbose:
            print(f"  d={d:>3} c={c} w={str(w):>4} sigma={sig:<4}: ref={ref:.12f} "
                  f"struct={got:.12f}  rel={rel:.2e}  {'OK' if rel < 1e-9 else 'FAIL'}")
    return ok


if __name__ == '__main__':
    print("Validating structured block-circulant L^circ against the K x K reference:")
    print("PASS" if selftest() else "FAIL")


def circulant_rf_mmse_lag(x0, h, sigma, t_band, lam=1e-6, device='cuda',
                          dtype=torch.float64, sample_chunk=32, freq_chunk=64):
    """L^circ with the NOISE term held in LAG space: memory L*c^2 instead of d*c^2.

    psi_ab(m) = sum_j h_a[j] h_b[(j+m) mod d] inherits the band support of h, so only
    L = 2*t-1 lags are nonzero. Writing m = p-q,

        f_f^H (rho^{o n} o M) f_f = (1/d) sum_{|m|<t} e^{-2 pi i f m/d} psi(m)^n R_ab(m),
        R_ab(m) = (1/N) sum_n sum_q C_a[n,q+m] C_b[n,q].

    TRADE-OFF, measured: this is a MEMORY result, not a compute one. Each lag costs c^2 N d
    (it contracts over n AND q) while each frequency costs c^2 N, so the lag form uses
    L = 2t-1 times MORE flops than the frequency form for L/d times less storage. At
    d=3072, c=3072, t=8: 432 GB -> 2.1 GB, and 2.9e14 -> 4.3e15 MACs.

    The DATA term is not banded (phi = relu(Theta y) is dense whatever Theta is), so it is
    streamed one frequency-chunk at a time rather than stored.
    """
    x0 = x0.to(device=device, dtype=dtype); h = h.to(device=device, dtype=dtype)
    N, d = x0.shape; c = h.shape[0]
    cdt = torch.complex128 if dtype == torch.float64 else torch.complex64
    L = 2 * t_band - 1
    lags = torch.arange(-(t_band - 1), t_band, device=device)

    mu = x0.mean(0); X0c = x0 - mu
    trace_p0 = float((X0c ** 2).sum() / max(N, 1))
    Xf = torch.fft.fft(x0.to(cdt), dim=1)
    Hf = torch.fft.fft(h.to(cdt), dim=1)
    nrm = torch.linalg.norm(h, dim=1); s = sigma * nrm

    # psi on the L nonzero lags only
    jj = torch.arange(d, device=device)
    psi = torch.stack([ (h * torch.roll(h, -int(m), dims=1).unsqueeze(0)).sum(-1)
                        if False else torch.einsum('aj,bj->ab', h, torch.roll(h, -int(m), dims=1))
                        for m in lags.tolist() ], dim=-1)                     # (c,c,L)
    psi = psi / (nrm.view(-1, 1, 1) * nrm.view(1, -1, 1))

    def feats(n0, n1):
        M = torch.fft.ifft(Xf[n0:n1].unsqueeze(0) * Hf.conj().unsqueeze(1), dim=2).real
        sa = s.view(-1, 1, 1); z = M / sa
        Phi = _ndtr(z); ph = _npdf(z)
        G = M * Phi + sa * ph
        return M, Phi, ph, G, sa

    # pass 1: per-(block,position) feature mean, and the L-lag noise correlations
    gmean = torch.zeros(c, d, dtype=dtype, device=device)
    nb = max(1, min(N, int(sample_chunk)))
    for n0 in range(0, N, nb):
        M, Phi, ph, G, sa = feats(n0, min(n0 + nb, N)); gmean += G.sum(1); del M, Phi, ph, G
    gmean /= N

    R = [torch.zeros(c, c, L, dtype=dtype, device=device) for _ in range(3)]
    diag_corr = torch.zeros(c, dtype=dtype, device=device)
    for n0 in range(0, N, nb):
        n1 = min(n0 + nb, N)
        M, Phi, ph, G, sa = feats(n0, n1)
        C = [sa * Phi, sa * ph / 2.0, -M * ph / 6.0]
        de = ((M ** 2 + sa ** 2) * Phi + M * sa * ph - G ** 2).sum(1)
        fo = (C[0] ** 2).sum(1) + 2.0 * (C[1] ** 2).sum(1) + 6.0 * (C[2] ** 2).sum(1)
        diag_corr += (de - fo).sum(1) / d
        for i in range(3):
            for li, m in enumerate(lags.tolist()):
                R[i][:, :, li] += torch.einsum('anq,bnq->ab', torch.roll(C[i], -m, dims=2), C[i])
        del M, Phi, ph, G, C
        torch.cuda.empty_cache()
    for i in range(3):
        R[i] /= N
    diag_corr /= N

    # pass 2: stream frequencies; data Gram computed on the fly, noise from the L lags
    v = X0c.to(cdt) @ _dft(d, device, dtype).to(cdt).T
    coef = (1.0, 2.0, 6.0)
    expl = 0.0
    fc = max(1, int(freq_chunk))
    for f0 in range(0, d, fc):
        f1 = min(f0 + fc, d); nf = f1 - f0
        fr = torch.arange(f0, f1, device=device)
        Uf = torch.zeros(nf, N, c, dtype=cdt, device=device)
        for n0 in range(0, N, nb):
            n1 = min(n0 + nb, N)
            M, Phi, ph, G, sa = feats(n0, n1)
            Gc = (G - gmean.unsqueeze(1)).to(cdt)
            E = torch.exp(-2j * np.pi * torch.outer(fr.to(dtype), jj.to(dtype)) / d) / d ** 0.5
            Uf[:, n0:n1, :] = torch.einsum('fp,anp->fna', E.to(cdt), Gc)
            del M, Phi, ph, G, Gc
        P = torch.einsum('fna,fnb->fab', Uf, Uf.conj()) / N
        q = torch.einsum('fna,nf->fa', Uf, v[:, f0:f1].conj()) / N
        ph_ = torch.exp(-2j * np.pi * torch.outer(fr.to(dtype), lags.to(dtype)) / d).to(cdt)
        for i in range(3):
            P = P + coef[i] * torch.einsum('fm,abm->fab', ph_,
                                           ((psi ** (i + 1)) * R[i]).to(cdt)) / d
        P = P + torch.diag_embed(diag_corr.to(cdt)).unsqueeze(0) \
              + lam * torch.eye(c, dtype=cdt, device=device).unsqueeze(0)
        sol = torch.linalg.solve(P, q.unsqueeze(-1)).squeeze(-1)
        expl += float(torch.real(torch.sum(q.conj() * sol)))
        del Uf, P, q; torch.cuda.empty_cache()
    return max(0.0, trace_p0 - expl)


def circulant_rf_mmse_lag2(x0, h, sigma, t_band, lam=1e-6, device='cuda',
                           dtype=torch.float64, sample_chunk=None, freq_chunk=32,
                           super_chunk=2048, verbose=False):
    """Same L^circ as `circulant_rf_mmse_lag`, restructured for speed.

    The old path recomputed the whole (c, N, d) feature tensor once per frequency chunk --
    384 full passes at freq_chunk=8 -- and that recomputation, not the linear algebra, was
    where the 3.75 h/seed at c=6144 went. Four changes, none of which touch the estimator:

    1. HERMITIAN SYMMETRY.  Sigma_phi and Sigma_{phi,x0} are real, so P_{d-f} = conj(P_f)
       and q_{d-f} = conj(q_f); the quadratic form q^H P^{-1} q at d-f is the conjugate of
       the one at f and contributes the SAME real part.  Only f = 0..d/2 is evaluated, with
       weight 2 except at f = 0 and f = d/2.  Halves everything in pass 2, including the
       number of feature passes.  rfft delivers exactly that frequency range.

    2. PREFIX-SUM ACCUMULATION.  The old code held u-hat for all N samples at once
       ((nf, N, c) complex = 983 MB per frequency at c=6144), which forced freq_chunk=8.
       Here P and q are running sums over sample super-chunks, so only (nf, NS, c) is live
       and freq_chunk can be 32-48 -- 6x fewer feature passes.

    3. LAG SYMMETRY.  R_ab(-m) = R_ba(m) and psi_ab(-m) = psi_ba(m), so only the t lags
       m = 0..t-1 are formed; the negative lags are the transposes.  The lag Grams are the
       dominant flop cost, so this is a straight 15/8 saving on them.

    4. FFT, NOT A DFT MATMUL.  u-hat was formed as an explicit (nf, d) x (c, nb, d) matmul
       costing c N d^2; rfft costs c N d log d.

    Validated against `circulant_rf_mmse_lag` and the K x K reference by `selftest_lag2`.
    """
    x0 = x0.to(device=device, dtype=dtype); h = h.to(device=device, dtype=dtype)
    N, d = x0.shape; c = h.shape[0]
    if d % 2 != 0:
        raise ValueError("Hermitian folding below assumes even d")
    cdt = torch.complex128 if dtype == torch.float64 else torch.complex64
    t = int(t_band); dh = d // 2 + 1
    sq = d ** 0.5

    if sample_chunk is None:                      # keep (c, nb, d) fp64 near 2 GB
        sample_chunk = max(1, min(N, int(2.0e9 / (c * d * 8))))
    nb = int(sample_chunk)

    mu = x0.mean(0); X0c = x0 - mu
    trace_p0 = float((X0c ** 2).sum() / max(N, 1))
    Xr = torch.fft.rfft(x0, dim=1)                        # (N, dh)
    Hr = torch.fft.rfft(h, dim=1)                         # (c, dh)
    vh = torch.fft.rfft(X0c, dim=1) / sq                  # (N, dh) == v[:, :dh]
    nrm = torch.linalg.norm(h, dim=1); s = sigma * nrm

    # psi on the non-negative lags only; psi(-m) = psi(m)^T
    psi = torch.stack([torch.einsum('aj,bj->ab', h, torch.roll(h, -m, dims=1))
                       for m in range(t)], dim=-1)                        # (c, c, t)
    psi /= (nrm.view(-1, 1, 1) * nrm.view(1, -1, 1))

    def feats(n0, n1):
        M = torch.fft.irfft(Xr[n0:n1].unsqueeze(0) * Hr.conj().unsqueeze(1), n=d, dim=2)
        sa = s.view(-1, 1, 1); z = M / sa
        Phi = _ndtr(z); ph = _npdf(z)
        G = M * Phi + sa * ph
        return M, Phi, ph, G, sa

    # ---- pass 1: feature mean, exact-diagonal correction, and the t lag Grams ----------
    gmean = torch.zeros(c, d, dtype=dtype, device=device)
    R = [torch.zeros(c, c, t, dtype=dtype, device=device) for _ in range(3)]
    diag_corr = torch.zeros(c, dtype=dtype, device=device)
    for n0 in range(0, N, nb):
        n1 = min(n0 + nb, N)
        M, Phi, ph, G, sa = feats(n0, n1)
        gmean += G.sum(1)
        C = [sa * Phi, sa * ph / 2.0, -M * ph / 6.0]
        de = ((M ** 2 + sa ** 2) * Phi + M * sa * ph - G ** 2).sum(1)
        fo = (C[0] ** 2).sum(1) + 2.0 * (C[1] ** 2).sum(1) + 6.0 * (C[2] ** 2).sum(1)
        diag_corr += (de - fo).sum(1) / d
        del M, Phi, ph, G
        for i in range(3):
            flat = C[i].reshape(c, -1)
            for m in range(t):
                R[i][:, :, m].addmm_(torch.roll(C[i], -m, dims=2).reshape(c, -1), flat.T)
        del C
    gmean /= N
    for i in range(3):
        R[i] /= N
    diag_corr /= N

    # Noise lag tensor, REAL and contiguous in the lag axis, with the Hermite coefficients
    # folded in and the negative lags materialised as transposes:
    #     B[:, :, i*L + (t-1) + m] = coef_i * psi(m)^{i+1} o R_i(m),   B[..., -m] = that^T.
    # Keeping it real and in ONE axis turns the whole noise assembly into two (c^2, 3L) x
    # (3L, nf) matmuls per frequency chunk. The obvious alternative -- a Python loop over
    # the 3L lags accumulating e^{-2pi i f m/d} * A_m into P -- allocates an (nf, c, c)
    # COMPLEX temporary 45 times per chunk, which at c=6144 is 45 x 19 GB of memory traffic
    # per chunk and is slower than the code this replaces.
    coef = (1.0, 2.0, 6.0)
    L = 2 * t - 1
    B = torch.empty(c, c, 3 * L, dtype=dtype, device=device)
    for i in range(3):
        for m in range(t):
            Am = (psi[:, :, m] ** (i + 1)) * R[i][:, :, m]
            B[:, :, i * L + (t - 1) + m] = coef[i] * Am
            if m > 0:
                B[:, :, i * L + (t - 1) - m] = coef[i] * Am.T
            del Am
    del R, psi
    lagvec = torch.arange(-(t - 1), t, device=device, dtype=dtype).repeat(3)   # (3L,)
    eye = torch.eye(c, dtype=cdt, device=device)
    dgc = torch.diag_embed(diag_corr.to(cdt))

    # ---- pass 2: stream f = 0..d/2, accumulating P and q over sample super-chunks ------
    expl = 0.0
    fc = max(1, int(freq_chunk)); NS = max(nb, int(super_chunk))
    for f0 in range(0, dh, fc):
        f1 = min(f0 + fc, dh); nf = f1 - f0
        P = torch.zeros(nf, c, c, dtype=cdt, device=device)
        q = torch.zeros(nf, c, dtype=cdt, device=device)
        for ns0 in range(0, N, NS):
            ns1 = min(ns0 + NS, N)
            buf = torch.zeros(nf, ns1 - ns0, c, dtype=cdt, device=device)
            for n0 in range(ns0, ns1, nb):
                n1 = min(n0 + nb, ns1)
                M, Phi, ph, G, sa = feats(n0, n1)
                U = torch.fft.rfft(G - gmean.unsqueeze(1), dim=2)[:, :, f0:f1] / sq
                buf[:, n0 - ns0:n1 - ns0, :] = U.permute(2, 1, 0)
                del M, Phi, ph, G, U
            P += buf.transpose(1, 2) @ buf.conj()
            q += (buf.transpose(1, 2) @ vh[ns0:ns1, f0:f1].conj().T.unsqueeze(-1)).squeeze(-1)
            del buf
        P /= N; q /= N
        fr = torch.arange(f0, f1, device=device, dtype=dtype)
        ang = -2.0 * np.pi * torch.outer(fr, lagvec) / d                  # (nf, 3L)
        Pv = torch.view_as_real(P)                                        # (nf, c, c, 2)
        for part, trig in ((0, torch.cos), (1, torch.sin)):
            Pv[..., part] += torch.einsum('fm,abm->fab', trig(ang), B) / d
        del Pv
        P += dgc.unsqueeze(0) + lam * eye.unsqueeze(0)
        sol = torch.linalg.solve(P, q.unsqueeze(-1)).squeeze(-1)
        term = torch.real(torch.sum(q.conj() * sol, dim=1))                # (nf,)
        wgt = torch.where((fr == 0) | (fr == d // 2), 1.0, 2.0)
        expl += float((term * wgt).sum())
        del P, q, sol
        if verbose:
            print(f"    f {f1}/{dh}", flush=True)
        torch.cuda.empty_cache()
    return max(0.0, trace_p0 - expl)


def selftest_lag2(seed=0, verbose=True):
    """lag2 vs the K x K reference AND vs the original lag path, banded filters only."""
    from core.rf_circulant import build_circulant_theta
    from core.rf_circulant_torch import circulant_rf_mmse_t
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    ok = True
    for (d, c, N, sig, w) in ((8, 3, 400, 1.3, 3), (16, 4, 800, 1.0, 5),
                              (16, 3, 800, 2.0, 2), (12, 24, 600, 0.7, 4),
                              (8, 32, 400, 0.5, 3), (32, 8, 900, 1.1, 6)):
        rng = np.random.default_rng(seed)
        A = rng.standard_normal((d, d)) * 0.6
        x0 = torch.tensor(rng.standard_normal((N, d)) @ A.T + 0.3, dtype=torch.float64,
                          device=dev)
        Theta = build_circulant_theta(c * d, d, np.random.default_rng(seed + 1), w=w)
        hh = torch.tensor(np.stack([Theta[a * d] for a in range(c)]), dtype=torch.float64,
                          device=dev)
        U0 = torch.zeros(N, 1, dtype=torch.float64, device=dev)
        G0 = torch.zeros(c * d, 1, dtype=torch.float64, device=dev)
        ref = circulant_rf_mmse_t(x0, U0, Theta, G0, sig, 1e-6, conditional=False,
                                  device=dev, dtype=torch.float64)
        ref = float(ref['loss'] if isinstance(ref, dict) else ref)
        old = circulant_rf_mmse_lag(x0, hh, sig, w, lam=1e-6, device=dev,
                                    sample_chunk=7, freq_chunk=3)
        new = circulant_rf_mmse_lag2(x0, hh, sig, w, lam=1e-6, device=dev,
                                     sample_chunk=7, freq_chunk=3, super_chunk=13)
        r1 = abs(new - ref) / max(abs(ref), 1e-12)
        r2 = abs(new - old) / max(abs(old), 1e-12)
        ok &= (r1 < 1e-9 and r2 < 1e-9)
        if verbose:
            print(f"  d={d:>3} c={c:>3} t={w} sigma={sig:<4}: ref={ref:.12f} "
                  f"lag2={new:.12f}  rel(ref)={r1:.2e} rel(lag)={r2:.2e} "
                  f"{'OK' if (r1 < 1e-9 and r2 < 1e-9) else 'FAIL'}")
    return ok
