"""IS Z_32 x Z_32 THE RIGHT GROUP?  Re-indexed nonlinear circulant RF on raw CIFAR pixels.

Everything is held fixed against `scripts/rf_pixel_featmatch2.py` except the GROUP:

    Z_3072 (that script)          Z_32 x Z_32 + free 3-channel mixing (this one)
    -------------------------     -------------------------------------------------
    Theta: c blocks, each a        Theta: c feature planes, each a 2-D cyclic conv over
      3072 x 3072 circulant                (3, 32, 32) with t x t taps summed over the 3
      generated by an 8-tap                input channels -> 3*t^2 = 27 random numbers per
      filter -> c*8 random nums            plane at t=3
    rows / features: c * 3072      features: c * 1024
    W: block-circulant, c*3072     W: BCCB on Z_32 x Z_32 with a free 3x3 channel mixing at
       trained params                 every frequency -> 3 * c * 1024 = 3072c trained params

so the TRAINED parameter count is identical (3072c) and `c` still means the same thing on
the free-parameter axis: c = k matches dense at k rows.  The random parameter count goes
c*8 -> c*27.  The feature count DROPS by 3x.  The only thing that really changes is which
symmetry the model is forced to respect.

Reference points already measured (excess over the Wiener optimum, tables/):
    linear class Z_3072                +1.273 / +4.070 / +8.473 / +9.005
    linear class Z_32 x Z_32 + 3ch     +0.889 / +3.082 / +6.469 / +7.782   <- the target
    nonlinear Z_3072 RF, c=1536        +0.177 / +2.968 / +8.320 / +8.975
at sigma = 0.127 / 0.452 / 1.610 / 5.0.  The linear shadow says the re-index is worth
0.38 / 0.99 / 2.00 / 1.22; the question this run answers is how much of that the NONLINEAR
model actually collects, and whether it is enough to go below the Wiener line at sigma=0.127.

    CS=256,512,1536 SIGS=0.127,0.452,1.610,5.0 python scripts/rf_pixel_circ2d.py
"""
import sys, os, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np, torch, torchvision, torchvision.transforms as T
from core.rf_circulant2d import circulant2d_rf_mmse

DEV = 'cuda'; DT = torch.float64; LAM = 1e-6
H = W = 32; CIN = 3; d = CIN * H * W
T2 = int(os.environ.get('T2', '3'))
CS = [int(x) for x in os.environ.get('CS', '256,512,1536').split(',')]
SIGS = [float(x) for x in os.environ.get('SIGS', '0.127,0.452,1.610,5.0').split(',')]
NIMG = int(os.environ.get('NIMG', '10000'))
NSEED = int(os.environ.get('NSEED', '4'))
OUT = os.environ.get('OUT', 'tables/rf_pixel_circ2d.npz')


def load():
    ds = torchvision.datasets.CIFAR10('/n/home12/binxuwang/.keras/datasets', train=True,
                                      download=False, transform=T.ToTensor())
    dl = torch.utils.data.DataLoader(ds, batch_size=512, num_workers=4)
    im = []
    for xb, _ in dl:
        im.append(xb)
        if sum(o.shape[0] for o in im) >= NIMG:
            break
    return torch.cat(im)[:NIMG].to(DEV, DT)          # (N, 3, 32, 32)


def sizing(c):
    """P is (nf, c, c) complex128 plus an (nf, c, c) fp64 einsum temporary, the sample
    buffer is (nf, NS, c) complex128, and -- unlike the 1-D driver -- the lag tensor
    B = (c, c, 3*(2t-1)^2) fp64 is large enough to matter (22.6 GB at c=6144, where the
    1-D B is 13.6 GB), so it is subtracted from the budget before nf is chosen."""
    nlag = 3 * (2 * T2 - 1) ** 2
    nf = int(min(64, max(4, (30e9 - c * c * nlag * 8) / (c * c * 24))))
    ns = int(min(NIMG, max(256, 6e9 / (nf * c * 16))))
    return nf, ns


def main():
    X = load(); N = X.shape[0]
    Xf = X.reshape(N, d)
    Xc = Xf - Xf.mean(0)
    ev = torch.linalg.eigvalsh((Xc.T @ Xc) / N)
    print(f"Z_32 x Z_32 RF, raw pixels  N={N}  Cin={CIN} {H}x{W}  t={T2} "
          f"({CIN * T2 * T2} random numbers/plane)  Tr(Sigma)={float(ev.sum()):.3f}  "
          f"seeds={NSEED}", flush=True)
    del Xf, Xc

    store = {}
    if os.path.exists(OUT):
        store = {k: v for k, v in np.load(OUT, allow_pickle=True).items()}
        print(f"resuming from {OUT}: {len(store)} cells already present", flush=True)

    for sg in SIGS:
        lin = float((sg ** 2 * ev / (ev + sg ** 2)).sum())
        store[f'linear|{sg}'] = np.array(lin)
        print(f"\n=== sigma={sg}   Wiener={lin:.4f} ===", flush=True)
        for c in CS:
            key = f'{sg}|{c}'
            if f'{key}|circ2d' in store:
                print(f"  c={c}: already done ({np.mean(store[key + '|circ2d']):.4f}), "
                      f"skipping", flush=True)
                continue
            nf, ns = sizing(c)
            cv = []
            for s in range(NSEED):
                t1 = time.time()
                g = torch.Generator(device=DEV); g.manual_seed(900 + 11 * s + c)
                h = torch.zeros(c, CIN, H, W, device=DEV, dtype=DT)
                h[:, :, :T2, :T2] = torch.randn(c, CIN, T2, T2, generator=g, device=DEV,
                                                dtype=DT) / np.sqrt(CIN * T2 * T2)
                cv.append(circulant2d_rf_mmse(X, h, sg, T2, lam=LAM, device=DEV,
                                              freq_chunk=nf, super_chunk=ns))
                print(f"      [seed {s}: {cv[-1]:.4f}  {time.time()-t1:.0f}s  nf={nf} "
                      f"NS={ns}  peak {torch.cuda.max_memory_allocated()/2**30:.1f} GB]",
                      flush=True)
                del h; torch.cuda.empty_cache(); torch.cuda.reset_peak_memory_stats()
            store[f'{key}|circ2d'] = np.array(cv)
            np.savez(OUT, **store)
            cm = float(np.mean(cv))
            sd = float(np.std(cv, ddof=1)) if NSEED > 1 else 0.0
            print(f"  >> c={c} ({CIN * H * W * c:,} trained params, {c * H * W:,} features): "
                  f"{cm:.4f} +-{sd:.4f}   excess over Wiener {cm - lin:+.4f}", flush=True)
    print("\ndone", flush=True)


if __name__ == '__main__':
    main()
