"""FEATURE-MATCH on raw CIFAR-10 pixels: block-circulant vs dense at EQUAL FREE PARAMETERS.

Setup (identical on both sides except the law of Theta and the constraint on W):
    x0  = raw CIFAR-10 pixel vector, d = 3072, [0,1] units, NOT standardized.
          N = 10,000 train images,  Tr(Sigma_p0) = 191.52.
    y   = x0 + sigma Z,   D(y) = W relu(Theta y) + b,  b free, unconditional.
    Sigma_phi from the Stein/Mehler analytic estimator on BOTH sides (no sampling of Z),
    ridge lam = 1e-6.

    dense      Theta in R^{k x d}, iid N(0, 1/d)  -> E||theta_i||^2 = 1.  k = j*d rows.
               free params: k*d in Theta, k*d in W.
    circulant  c blocks; block a is the d x d circulant generated by h_a, supported on the
               first t taps with h_a[:t] ~ N(0, I/t) -> E||h_a||^2 = 1, so every one of its
               rows is norm-matched to a dense row.  W block-circulant.
               free params: c*d in Theta, c*d in W.   ROWS: c*d.

    Matching free parameters therefore means  c = k = j*d,  which gives the circulant
    d = 3072 times MORE rows than the dense model it is matched against.

Uses core.rf_circulant_struct.circulant_rf_mmse_lag2 (Hermitian-folded, prefix-sum
accumulated); see that docstring for why it is ~N times faster than the path that produced
the August numbers.  Results are appended to tables/rf_pixel_featmatch2.npz after every
(sigma, j) cell so a killed allocation never loses more than one cell, and a restart skips
what is already there.

    JS=0.5,1,2  SIGS=0.127,0.452,1.610  python scripts/rf_pixel_featmatch2.py
"""
import sys, os, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np, torch, torchvision, torchvision.transforms as T
from core.rf_circulant_struct import circulant_rf_mmse_lag2
from core.rf_gmm_estimators_torch import stein_finiteN_mmse_t

DEV = 'cuda'; DT = torch.float64; d = 3072; LAM = 1e-6
T_BAND = int(os.environ.get('T_BAND', '8'))
JS = [float(x) for x in os.environ.get('JS', '0.5,1,2').split(',')]
SIGS = [float(x) for x in os.environ.get('SIGS', '0.127,0.452,1.610').split(',')]
NIMG = int(os.environ.get('NIMG', '10000'))
NSEED = int(os.environ.get('NSEED', '2'))
# Circulant seeds are budgeted separately: a circ cell costs 250-2561 s while a dense cell
# costs 1-5 s, and the circulant SELF-AVERAGES -- measured seed spread is +-0.0017 (c=1536),
# +-0.0004 (c=3072), +-0.0001 (c=6144), because c blocks x t taps is 12k-49k independent
# random numbers.  (The "never quote a single-draw circulant number" rule was established at
# c=2, i.e. 16 random numbers, and does not apply at these widths.)  Dense keeps NSEED
# because its spread is real (+-0.15 at k/d=0.5) and it is free.
NSEED_CIRC = int(os.environ.get('NSEED_CIRC', str(NSEED)))
OUT = os.environ.get('OUT', 'tables/rf_pixel_featmatch2.npz')


def load():
    ds = torchvision.datasets.CIFAR10('/n/home12/binxuwang/.keras/datasets', train=True,
                                      download=False, transform=T.ToTensor())
    dl = torch.utils.data.DataLoader(ds, batch_size=512, num_workers=4)
    im = []
    for xb, _ in dl:
        im.append(xb.reshape(xb.shape[0], -1))
        if sum(o.shape[0] for o in im) >= NIMG:
            break
    return torch.cat(im)[:NIMG].to(DEV, DT)


def sizing(c):
    """freq_chunk / super_chunk from the two tensors that actually bind on an 80 GB card:
    P is (nf, c, c) complex128 plus an (nf, c, c) fp64 einsum temporary, and the sample
    buffer is (nf, NS, c) complex128."""
    nf = int(min(64, max(4, 30e9 / (c * c * 24))))
    ns = int(min(NIMG, max(256, 6e9 / (nf * c * 16))))
    return nf, ns


def main():
    X = load(); N = X.shape[0]
    Xc = X - X.mean(0); ev = torch.linalg.eigvalsh((Xc.T @ Xc) / N)
    U = torch.zeros(N, 1, dtype=DT, device=DEV)
    print(f"FEATURE-MATCH raw pixels d={d} N={N} Tr(Sigma)={float(ev.sum()):.3f} t={T_BAND} "
          f"seeds={NSEED} (circ {NSEED_CIRC})", flush=True)

    store = {}
    if os.path.exists(OUT):
        store = {k: v for k, v in np.load(OUT, allow_pickle=True).items()}
        print(f"resuming from {OUT}: {len(store)} cells already present", flush=True)

    for sg in SIGS:
        lin = float((sg ** 2 * ev / (ev + sg ** 2)).sum())
        store[f'linear|{sg}'] = np.array(lin)
        print(f"\n=== sigma={sg}   linear={lin:.4f} ===", flush=True)
        for j in JS:
            key = f'{sg}|{j}'
            if f'{key}|circ' in store:
                print(f"  j={j}: already done, skipping", flush=True)
                continue
            k = int(round(j * d)); c = k
            nf, ns = sizing(c)

            t0 = time.time()
            dv = []
            for s in range(NSEED):
                Th = np.random.default_rng(3 + s).standard_normal((k, d)) / np.sqrt(d)
                G = torch.zeros(k, 1, dtype=DT, device=DEV)
                dv.append(float(stein_finiteN_mmse_t(X, U, Th, G, sg, LAM,
                                                     conditional=False, device=DEV, dtype=DT)))
                del G, Th; torch.cuda.empty_cache()
            td = time.time() - t0
            print(f"  j={j} k=c={k}: dense = {np.mean(dv):.4f}"
                  f"+-{np.std(dv, ddof=1) if NSEED > 1 else 0:.4f}  [{td:.0f}s]", flush=True)

            cv = []
            for s in range(NSEED_CIRC):
                t1 = time.time()
                g = torch.Generator(device=DEV); g.manual_seed(800 + 11 * s + c)
                h = torch.zeros(c, d, device=DEV, dtype=DT)
                h[:, :T_BAND] = torch.randn(c, T_BAND, generator=g, device=DEV,
                                            dtype=DT) / np.sqrt(T_BAND)
                cv.append(circulant_rf_mmse_lag2(X, h, sg, T_BAND, lam=LAM, device=DEV,
                                                 freq_chunk=nf, super_chunk=ns))
                print(f"      [circ seed {s}: {cv[-1]:.4f}  {time.time()-t1:.0f}s  "
                      f"nf={nf} NS={ns}  peak {torch.cuda.max_memory_allocated()/2**30:.1f} GB]",
                      flush=True)
                del h; torch.cuda.empty_cache(); torch.cuda.reset_peak_memory_stats()

            dm, cm = float(np.mean(dv)), float(np.mean(cv))
            store[f'{key}|dense'] = np.array(dv)
            store[f'{key}|circ'] = np.array(cv)
            np.savez(OUT, **store)
            print(f"  >> j={j}: dense(k={k}, {k*d:,} params) = {dm:.4f} | "
                  f"circ(c={c}, {c*d:,} rows, {c*d:,} params) = {cm:.4f}"
                  f"+-{np.std(cv, ddof=1) if NSEED_CIRC > 1 else 0:.4f}  ({cm-dm:+.4f})  "
                  f"linear={lin:.4f}", flush=True)
    print("\ndone", flush=True)


if __name__ == '__main__':
    main()
