"""BAND-MODULATED *NONLINEAR* RF ON Z_32 x Z_32, HELD OUT (michimin, 2026-09-23 06:36).

    "run B=1 experiment for 2D circulant for c=512 for all the noises"

THE QUESTION THIS DECIDES.  Every band number this project has is LINEAR -- rf_band_relaxation
(michimin's), rf_band_relaxation_atlas.py and rf_band_relaxation_heldout.py all measure the
best LINEAR map in the band class, i.e. the toll.  The load-bearing untested assumption behind
michimin's section 5 is that the NONLINEAR gain measured in the small class,

    gain = L[best linear in the class] - L[the relu RF in the same class],

SURVIVES when the linear class is enlarged.  The default worry runs the other way: a larger
linear class absorbs what relu bought, and the gain shrinks.  Held out at c = 1536 the plain
2-D arm has gain 1.870 at sigma=0.127; the band B=1 class is 9x larger and its linear toll is
0.200 instead of 0.441.  If the nonlinear gain is intact, the band RF should land near
    L^lin(B=1) - gain  =  (Wiener + 0.200) - gain,
and if it is absorbed it will land near L^lin(B=1) itself.  Both outcomes are informative and
they are far apart -- about 1.9 in a quantity whose total spread is ~2.

WHY THIS RUN MUST BE HELD OUT, NOT IN SAMPLE.  Trained parameters = Cin*c*H*W*(2B+1)^2, which
at c=512, B=1 is *14,155,776* -- 9x the plain 2-D arm at the same c and THREE TIMES the free
Wiener's 9,437,184 -- against 10,000 images.  That is squarely the regime where the dense RF
was caught memorising on 2026-09-21 (its advantage over linear collapsed 0.825 -> 0.336 ->
0.039 as N went 10k -> 20k -> 40k, with lam=1e-6 doing nothing).  An in-sample number here
would be uninterpretable.  Both the RF and the Wiener baseline are therefore fitted on
train[:10000] and scored on the 10,000 CIFAR TEST images, exactly as in
scripts/rf_pixel_heldout.py.

PAIRED WITH THE PLAIN ARM BY CONSTRUCTION.  `filt2d` mirrors scripts/rf_pixel_heldout.py seed
for seed, so at a given (sigma, c, seed) the band model and the plain 2-D model in
tables/rf_pixel_heldout.npz use the IDENTICAL random filters.  The band-vs-plain differential
is then a paired comparison on one Theta draw, not a difference of two independent draws --
which matters, because a banded circulant Theta is generated by only c*Cin*t^2 random numbers
and Var_Theta(L) is Theta(1), not o(1) (2026-08-17).  B=0 is asserted against the stored plain
cells for the same reason it is asserted in the plain driver.

    CS=512 BS=1 SIGS=0.127 python scripts/rf_pixel_band2d_heldout.py
"""
import sys, os, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np, torch
from core.rf_circulant2d_band import circulant2d_band_rf_mmse, band_offsets
from scripts.rf_pixel_heldout import load, linear_split, filt2d, DEV, DT, LAM, H, W, CIN, d

T2 = int(os.environ.get('T2', '3'))
CS = [int(x) for x in os.environ.get('CS', '512').split(',')]
BS = [int(x) for x in os.environ.get('BS', '1').split(',')]
SIGS = [float(x) for x in
        os.environ.get('SIGS', '0.127,0.452,0.621,0.853,1.172,1.610,2.212,5.0').split(',')]
NIMG = int(os.environ.get('NIMG', '10000'))
NTEST = int(os.environ.get('NTEST', '10000'))
NSEED = int(os.environ.get('NSEED', '1'))
BUDGET = float(os.environ.get('BUDGET', '34e9'))
OUT = os.environ.get('OUT', 'tables/rf_pixel_band2d_heldout.npz')
PLAIN = 'tables/rf_pixel_heldout.npz'


def sizing(c, B):
    """Pick freq_chunk / super_chunk from a GPU budget.

    The binders, all of which are live at once on the held-out path because train and test
    moments are both resident:
      Bc         nD * c^2 * 3(2t-1)^2 * 16 B  per split   (Delta-resolved Stein lag tensor)
      P, q       nf * K^2 * 16 B              per split,  K = c(2B+1)^2
      buf        nf * ns * K * 16 B           one split at a time
    nD = |box(2B) half| = ((2*(2B)+1)^2 + 1) / 2.
    """
    nG = (2 * B + 1) ** 2
    K = c * nG
    nD = ((4 * B + 1) ** 2 + 1) // 2
    fixed = 2 * nD * c * c * 3 * (2 * T2 - 1) ** 2 * 8 * 2      # Bc, both splits (complex)
    left = max(2e9, BUDGET - fixed)
    nf = int(min(16, max(1, left / (2 * K * K * 16 * 2.2))))     # P for both splits + slack
    ns = int(min(max(NIMG, NTEST), max(256, 3e9 / (nf * K * 16))))
    return nf, ns


def main():
    Xtr = load(True, NIMG)
    Xte = load(False, NTEST)
    print(f"BAND-MODULATED NONLINEAR RF, held out.  train={Xtr.shape[0]}  test={Xte.shape[0]}"
          f"  c={CS}  B={BS}  seeds={NSEED}", flush=True)
    Xtr1 = Xtr.reshape(Xtr.shape[0], d)
    Xte1 = Xte.reshape(Xte.shape[0], d)

    store = {}
    if os.path.exists(OUT):
        store = {k: v for k, v in np.load(OUT, allow_pickle=True).items()}
        print(f"resuming from {OUT}: {len(store)} cells already present", flush=True)
    plain = dict(np.load(PLAIN, allow_pickle=True)) if os.path.exists(PLAIN) else {}

    for sg in SIGS:
        lin_tr, lin_te = linear_split(Xtr1, Xte1, sg)
        store[f'linear|{sg}'] = np.array([lin_tr, lin_te])
        print(f"\n=== sigma={sg}   Wiener train={lin_tr:.4f}  test={lin_te:.4f} ===",
              flush=True)
        for c in CS:
            for B in BS:
                key = f'{sg}|{c}|{B}'
                nG = (2 * B + 1) ** 2
                npar = CIN * c * H * W * nG
                if key in store:
                    v = store[key]
                    print(f"  B={B} c={c}: already done (train {np.mean(v[:, 0]):.4f}  "
                          f"test {np.mean(v[:, 2]):.4f})", flush=True)
                    continue
                nf, ns = sizing(c, B)
                rows = []
                for s in range(NSEED):
                    t1 = time.time()
                    r = circulant2d_band_rf_mmse(Xtr, filt2d(c, s), sg, T2, B, lam=LAM,
                                                 device=DEV, freq_chunk=nf, super_chunk=ns,
                                                 x0_test=Xte)
                    rows.append([r['train'], r['train_resid'], r['test']])
                    print(f"      [seed {s}: train {r['train']:.4f}  "
                          f"resid {r['train_resid']:.4f}  test {r['test']:.4f}  "
                          f"{time.time()-t1:.0f}s  nf={nf} NS={ns}  "
                          f"peak {torch.cuda.max_memory_allocated()/2**30:.1f} GB]",
                          flush=True)
                    torch.cuda.empty_cache(); torch.cuda.reset_peak_memory_stats()
                a = np.array(rows)
                store[key] = a
                np.savez(OUT, **store)
                tr_m, te_m = float(a[:, 0].mean()), float(a[:, 2].mean())
                print(f"  >> B={B} c={c} ({npar:,} trained params): "
                      f"train {tr_m:.4f} ({tr_m-lin_tr:+.4f})   "
                      f"test {te_m:.4f} ({te_m-lin_te:+.4f} vs held-out Wiener)   "
                      f"own gap {te_m-float(a[:, 1].mean()):+.4f}", flush=True)

                # PAIRED DIFFERENTIAL against the plain 2-D arm on the SAME filters.
                p = plain.get(f'{sg}|{c}|2d')
                if p is not None:
                    n = min(len(p), len(a))
                    dte = float(np.mean(a[:n, 2] - np.asarray(p)[:n, 2]))
                    print(f"     [band B={B} - plain 2-D at c={c}, same Theta draws: "
                          f"{dte:+.4f} held out  (plain test {np.mean(np.asarray(p)[:n,2]):.4f})]",
                          flush=True)
                    # B=0 IS the plain model -- any drift means the band path moved it.
                    if B == 0:
                        dv = float(np.abs(np.asarray(p)[:n, 0] - a[:n, 0]).max())
                        print(f"     [B=0 reproduces the plain held-out table: "
                              f"max|delta| = {dv:.2e}]", flush=True)
                        assert dv < 1e-8, f"{key} does not reproduce the plain table: {dv}"
    print("\ndone", flush=True)


if __name__ == '__main__':
    main()
